# Generated by Django 4.2.7 on 2023-11-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_images_alter_comment_id_alter_post_id'),
    ]

    operations = [
    ]
